// Social sharing helpers. The OG image is generated by /api/og.

import type { Submission } from "./types";

export interface SharePayload {
  submission_id: string;
  title: string;
  severity: number | null;
  display_score: number;
  period_label: string;
  city: string;
}

export function payloadFromSubmission(
  s: Submission,
  periodLabel = "current period",
  city = process.env.NEXT_PUBLIC_DEFAULT_CITY ?? "your city",
): SharePayload {
  return {
    submission_id: s.id,
    title: s.title,
    severity: s.severity,
    display_score: s.display_score,
    period_label: periodLabel,
    city,
  };
}

function submissionUrl(p: SharePayload, origin: string): string {
  return `${origin}/suggestions/${p.submission_id}`;
}

export const shareTargets = {
  twitter(p: SharePayload, origin: string): string {
    const url = submissionUrl(p, origin);
    const text = `"${p.title}" needs attention in ${p.city} — severity ${p.severity ?? "?"}/4. Vote now:`;
    return `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`;
  },

  changeOrg(_p: SharePayload, _origin: string): string {
    return "https://www.change.org/start-a-petition";
  },

  discord(p: SharePayload, origin: string): unknown {
    return {
      embeds: [
        {
          title: p.title,
          description: `Severity: ${p.severity ?? "?"}/4 · Score: ${p.display_score}`,
          color: severityColor(p.severity ?? 1),
          url: submissionUrl(p, origin),
        },
      ],
    };
  },

  copyLink(p: SharePayload, origin: string) {
    if (typeof navigator !== "undefined" && navigator.clipboard) {
      return navigator.clipboard.writeText(submissionUrl(p, origin));
    }
    return Promise.resolve();
  },

  ogImage(p: SharePayload, origin: string): string {
    return `${origin}/api/og?submission_id=${encodeURIComponent(p.submission_id)}`;
  },
};

export function severityColor(severity: number): number {
  switch (severity) {
    case 4:
      return 0xef4444;
    case 3:
      return 0xfb923c;
    case 2:
      return 0xfbbf24;
    default:
      return 0x94a3b8;
  }
}
